name: pulse
description: A new Flutter application.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.0
  path: ^1.8.3
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^5.7.3
  firebase_storage: ^11.2.3

  google_maps_flutter: any

  url_launcher: ^6.2.6

  image_picker: any

  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3

  wave: ^0.2.2

  table_calendar: ^3.1.1
  flutter_svg: ^2.0.10+1

dependency_overrides:
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

