// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzv_L_zNI23uuXNYz7nh-90B9zwfcz2qs',
    appId: '1:257250602951:android:f845f5267b4813acc0b3e2',
    messagingSenderId: '257250602951',
    projectId: 'pulse-provider-app',
    databaseURL: 'https://pulse-provider-app-default-rtdb.firebaseio.com',
    storageBucket: 'pulse-provider-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-hDD-NrNONncGZ4cde1sHFEo7aSkD_k',
    appId: '1:257250602951:web:250822db4f98fb9dc0b3e2',
    messagingSenderId: '257250602951',
    projectId: 'pulse-provider-app',
    authDomain: 'pulse-provider-app.firebaseapp.com',
    databaseURL: 'https://pulse-provider-app-default-rtdb.firebaseio.com',
    storageBucket: 'pulse-provider-app.firebasestorage.app',
  );

}